apiVersion: config.liqo.io/v1alpha1
kind: ClusterConfig
metadata:
  name: configuration
  labels:
    app: liqo.io
spec:
  advertisementConfig:
    ingoingConfig:
      acceptPolicy: AutoAcceptMax
      maxAcceptableAdvertisement: 5
    outgoingConfig:
      resourceSharingPercentage: 30
      enableBroadcaster: true
    keepaliveThreshold: 3
    keepaliveRetryTime: 20
  agentConfig:
    dashboardConfig:
      namespace: {{ .Release.Namespace }}
      appLabel: "liqo-dashboard"
  discoveryConfig:
    clusterName: {{ .Values.clusterName }}
    autojoin: true
    autojoinUntrusted: true
    domain: local.
    enableAdvertisement: true
    enableDiscovery: true
    name: MyLiqo
    port: 6443
    service: _liqo_api._tcp
    ttl: 90
  authConfig:
    allowEmptyToken: true
  liqonetConfig:
    podCIDR: {{ .Values.podCIDR }}
    serviceCIDR: {{ .Values.serviceCIDR }}
    reservedSubnets:
    - {{ .Values.podCIDR }}
    - {{ .Values.serviceCIDR }}
  dispatcherConfig:
    resourcesToReplicate:
    - group: net.liqo.io
      version: v1alpha1
      resource: networkconfigs
