---
{{- $config := (merge (dict "name" "configuration" "module" "configuration") .) -}}

{{- $peeringBasic := (merge (dict "name" "remote-peering-basic" "module" "discovery") .) -}}
{{- $peeringIncoming := (merge (dict "name" "remote-peering-incoming" "module" "discovery") .) -}}
{{- $peeringOutgoing := (merge (dict "name" "remote-peering-outgoing" "module" "discovery") .) -}}

apiVersion: config.liqo.io/v1alpha1
kind: ClusterConfig
metadata:
  name: {{ include "liqo.prefixedName" $config }}
  labels:
    {{- include "liqo.labels" $config  | nindent 4 }}
spec:
  apiServerConfig:
    {{- .Values.apiServer | toYaml | nindent 4 }}
  resourceSharingConfig:
    ingoingConfig:
      acceptPolicy: AutoAcceptMax
      maxAcceptableAdvertisement: 1000000
    keepaliveThreshold: 3
    keepaliveRetryTime: 20
    outgoingConfig:
      {{- .Values.controllerManager.config | toYaml | nindent 6 }}
  discoveryConfig:
    {{- .Values.discovery.config | toYaml | nindent 4 }}
    domain: local.
    name: MyLiqo
    port: 6443
    service: _liqo_api._tcp
    {{- if .Values.auth.ingress.host}}
    authServiceAddress: "{{ .Values.auth.ingress.host }}"
    {{- end }}
    {{- if .Values.auth.portOverride }}
    authServicePort: "{{ .Values.auth.portOverride }}"
    {{- else if .Values.auth.ingress.enable }}
    authServicePort: "443"
    {{- end }}
  authConfig:
    {{- .Values.auth.config | toYaml | nindent 4 }}
    peeringPermission:
      basic:
      - {{ include "liqo.prefixedName" $peeringBasic }}
      incoming:
      - {{ include "liqo.prefixedName" $peeringIncoming }}
      outgoing:
      - {{ include "liqo.prefixedName" $peeringOutgoing }}
  liqonetConfig:
    {{- .Values.networkManager.config | toYaml | nindent 4 }}
  dispatcherConfig:
    resourcesToReplicate:
    - groupVersionResource:
        group: discovery.liqo.io
        version: v1alpha1
        resource: resourcerequests
      peeringPhase: Authenticated
    - groupVersionResource:
        group: sharing.liqo.io
        version: v1alpha1
        resource: resourceoffers
      peeringPhase: Incoming
    - groupVersionResource:
        group: net.liqo.io
        version: v1alpha1
        resource: networkconfigs
      peeringPhase: Established
