---
{{- $netManagerConfig := (merge (dict "name" "network-manager" "module" "networking") .) -}}

{{- if .Values.networking.internal }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $netManagerConfig }}
  labels:
  {{- include "liqo.labels" $netManagerConfig | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $netManagerConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.networkManager.pod.annotations }}
      annotations:
        {{- toYaml .Values.networkManager.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.labels" $netManagerConfig | nindent 8 }}
        {{- if .Values.networkManager.pod.labels }}
          {{- toYaml .Values.networkManager.pod.labels | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- include "liqo.podSecurityContext" . | nindent 8 }}
      serviceAccountName: {{ include "liqo.prefixedName" $netManagerConfig }}
      containers:
        - image: {{ .Values.networkManager.imageName }}{{ include "liqo.suffix" $netManagerConfig }}:{{ include "liqo.version" $netManagerConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          securityContext:
            {{- include "liqo.containerSecurityContext" . | nindent 12 }}
          name: {{ $netManagerConfig.name }}
          command: ["/usr/bin/liqonet"]
          ports:
            - name: ipam-api
              containerPort: 6000
          args:
            - --run-as=liqo-network-manager
            - --manager.pod-cidr={{ .Values.networkManager.config.podCIDR }}
            - --manager.service-cidr={{ .Values.networkManager.config.serviceCIDR }}
            {{- if .Values.networkManager.config.reservedSubnets }}
            {{- $d := dict "commandName" "--manager.reserved-pools" "list" .Values.networkManager.config.reservedSubnets }}
            {{- include "liqo.concatenateList" $d | nindent 12 }}
            {{- end }}
            {{- if .Values.networkManager.config.additionalPools }}
            {{- $d := dict "commandName" "--manager.additional-pools" "list" .Values.networkManager.config.additionalPools }}
            {{- include "liqo.concatenateList" $d | nindent 12 }}
            {{- end }}
            {{- if .Values.common.extraArgs }}
            {{- toYaml .Values.common.extraArgs | nindent 12 }}
            {{- end }}
            {{- if .Values.networkManager.pod.extraArgs }}
            {{- toYaml .Values.networkManager.pod.extraArgs | nindent 12 }}
            {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IPTABLES_MODE
              value: {{ .Values.networking.iptables.mode }}
          resources: {{- toYaml .Values.networkManager.pod.resources | nindent 12 }}
      {{- if ((.Values.common).nodeSelector) }}
      nodeSelector:
      {{- toYaml .Values.common.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).tolerations) }}
      tolerations:
      {{- toYaml .Values.common.tolerations | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).affinity) }}
      affinity:
      {{- toYaml .Values.common.affinity | nindent 8 }}
      {{- end }}
{{- end }}
