---
{{- $discoveryConfig := (merge (dict "name" "discovery" "module" "discovery") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
  labels:
    {{- include "liqo.labels" $discoveryConfig| nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.labels" $discoveryConfig| nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo.labels" $discoveryConfig| nindent 8 }}
      {{- if .Values.discovery.pod.labels }}
        {{- toYaml .Values.discovery.pod.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.discovery.pod.annotations }}
      annotations:
        {{- toYaml .Values.discovery.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $discoveryConfig}}
      containers:
        - image: {{ .Values.discovery.imageName }}{{ include "liqo.suffix" $discoveryConfig }}:{{ include "liqo.version" $discoveryConfig }}
          name: {{ $discoveryConfig.name }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/usr/bin/entrypoint.sh", "/usr/bin/discovery"]
          args:
          - "--namespace"
          - "$(POD_NAMESPACE)"
          - "--requeueAfter"
          - "30"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.apiServer.address }}
            - name: APISERVER
              value: "{{ .Values.apiServer.address }}"
            {{- end }}
            {{- if .Values.apiServer.port }}
            - name: APISERVER_PORT
              value: "{{ .Values.apiServer.port }}"
            {{- end }}
            {{- if .Values.auth.ingress.host}}
            - name: AUTH_ADDR
              value: "{{ .Values.auth.ingress.host }}"
            {{- end }}
            {{- if .Values.auth.ingress.port }}
            - name: AUTH_SVC_PORT
              value: "{{ .Values.auth.ingress.port }}"
            {{- end }}
          resources:
            limits:
              cpu: 50m
              memory: 50M
            requests:
              cpu: 50m
              memory: 50M
      hostNetwork: true
