# Default values for networkModule_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

routeOperator:
  image:
    repository: "liqo/liqonet"
    pullPolicy: "IfNotPresent"
tunnelEndpointOperator:
  image:
    repository: "liqo/liqonet"
    pullPolicy: "IfNotPresent"
