apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-operator
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: drone-operator
  template:
    metadata:
      labels:
        name: drone-operator
    spec:
      serviceAccountName: drone-operator
      # Add the ConfigMap as a volume to the Pod
      volumes:
        # `name` here must match the name specified in the volume mount
          - name: drone-operator-configmap-volume
          # Populate the volume with config map data
            configMap:
              # `name` here must match the name specified in the ConfigMap's YAML
              name: drone-operator-configmap
      containers:
        - name: drone-operator
          # Replace this with the built image name
          image: andreamora/drone-operator:first
          command:
          - drone-operator
          imagePullPolicy: Always
          tty: true # for format and color log
          volumeMounts:
            # `name` here must match the name from the volumes section of this pod
              - name: drone-operator-configmap-volume
                mountPath: /etc/config
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "drone-operator"
