
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: clusterconfigs.policy.liqo.io
spec:
  group: policy.liqo.io
  names:
    kind: ClusterConfig
    listKind: ClusterConfigList
    plural: clusterconfigs
    singular: clusterconfig
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterConfig is the Schema for the clusterconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterConfigSpec defines the desired state of ClusterConfig
          properties:
            advertisementConfig:
              properties:
                autoAccept:
                  type: boolean
                enableBroadcaster:
                  type: boolean
                maxAcceptableAdvertisement:
                  format: int32
                  minimum: 0
                  type: integer
                resourceSharingPercentage:
                  format: int32
                  maximum: 100
                  minimum: 0
                  type: integer
              required:
                - autoAccept
              type: object
            discoveryConfig:
              properties:
                autojoin:
                  type: boolean
                autojoinUntrusted:
                  type: boolean
                dnsServer:
                  type: string
                domain:
                  type: string
                enableAdvertisement:
                  type: boolean
                enableDiscovery:
                  type: boolean
                name:
                  type: string
                port:
                  maximum: 65355
                  minimum: 1
                  type: integer
                allowUntrustedCA:
                  type: boolean
                service:
                  type: string
                updateTime:
                  minimum: 2
                  type: integer
                waitTime:
                  minimum: 1
                  type: integer
              required:
              - autojoin
              - autojoinUntrusted
              - dnsServer
              - domain
              - enableAdvertisement
              - enableDiscovery
              - name
              - port
              - allowUntrustedCA
              - service
              - updateTime
              - waitTime
              type: object
            liqonetConfig:
              properties:
                gatewayPrivateIP:
                  type: string
                reservedSubnets:
                  description: contains a list of reserved subnets in CIDR notation
                    used by the k8s cluster like the podCIDR and ClusterCIDR
                  items:
                    type: string
                  type: array
                vxlanNetConfig:
                  properties:
                    DeviceName:
                      type: string
                    Network:
                      type: string
                    Port:
                      type: string
                    Vni:
                      type: string
                  required:
                  - DeviceName
                  - Network
                  - Port
                  - Vni
                  type: object
              required:
              - gatewayPrivateIP
              - reservedSubnets
              type: object
          required:
          - advertisementConfig
          - discoveryConfig
          - liqonetConfig
          type: object
        status:
          description: ClusterConfigStatus defines the observed state of ClusterConfig
          type: object
      type: object
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
