apiVersion: k3d.io/v1alpha3
kind: Simple
name: edgedns
image: docker.io/rancher/k3s:v1.30.2-k3s2
agents: 0
network: k3d-action-bridge-network
ports:
- port: 0.0.0.0:1053:30053/tcp
  nodeFilters:
  - server:0:direct
- port: 0.0.0.0:1053:30053/udp
  nodeFilters:
  - server:0:direct
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik,servicelb,metrics-server,local-storage
        nodeFilters:
          - server:*
      - arg: --cluster-cidr=10.40.0.0/16
        nodeFilters:
          - server:*
      - arg: --service-cidr=10.30.0.0/16
        nodeFilters:
          - server:*
