apiVersion: k3d.io/v1alpha3
kind: Simple
name: gslb-us
image: docker.io/rancher/k3s:v1.30.2-k3s2
agents: 1
network: k3d-action-bridge-network
ports:
  - port: 81:80
    nodeFilters:
      - agent:0:direct
  - port: 444:443
    nodeFilters:
      - agent:0:direct
  - port: 9081:30090
    nodeFilters:
      - agent:0:direct
  - port: 5054:30053/tcp
    nodeFilters:
      - agent:0:direct
  - port: 5054:53/udp
    nodeFilters:
      - agent:0:direct
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik,servicelb,metrics-server,local-storage
        nodeFilters:
          - server:*
      - arg: --cluster-cidr=10.40.0.0/16
        nodeFilters:
          - server:*
      - arg: --service-cidr=10.30.0.0/16
        nodeFilters:
          - server:*
