apiVersion: config.liqo.io/v1alpha1
kind: ClusterConfig
metadata:
  name: configuration
  labels:
    app: liqo.io
spec:
  advertisementConfig:
    ingoingConfig:
      acceptPolicy: AutoAcceptMax
      maxAcceptableAdvertisement: 5
    outgoingConfig:
      resourceSharingPercentage: 30
      enableBroadcaster: true
    keepaliveThreshold: 3
    keepaliveRetryTime: 20
  discoveryConfig:
    autojoin: true
    autojoinUntrusted: true
    domain: local.
    enableAdvertisement: true
    enableDiscovery: true
    name: MyLiqo
    port: 6443
    allowUntrustedCA: true
    service: _liqo._tcp
    updateTime: 3
    waitTime: 2
    dnsServer: '8.8.8.8:53'
  liqonetConfig:
    podCIDR: {{ .Values.podCIDR }}
    reservedSubnets:
    - {{ .Values.podCIDR }}
    - {{ .Values.serviceCIDR }}
  dispatcherConfig:
    resourcesToReplicate:
    - group: liqonet.liqo.io
      version: v1alpha1
      resource: networkconfigs
