
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: tunnelendpoints.dronet.drone.com
spec:
  group: dronet.drone.com
  names:
    kind: TunnelEndpoint
    listKind: TunnelEndpointList
    plural: tunnelendpoints
    singular: tunnelendpoint
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: TunnelEndpoint is the Schema for the endpoints API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TunnelEndpointSpec defines the desired state of TunnelEndpoint
          properties:
            clusterID:
              type: string
            podCIDR:
              type: string
            tunnelPrivateIP:
              type: string
            tunnelPublicIP:
              type: string
          required:
          - clusterID
          - podCIDR
          - tunnelPrivateIP
          - tunnelPublicIP
          type: object
        status:
          description: TunnelEndpointStatus defines the observed state of TunnelEndpoint
          properties:
            NAT:
              type: boolean
            localRemappedPodCIDR:
              type: string
            localTunnelPrivateIP:
              type: string
            localTunnelPublicIP:
              type: string
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file\'
              type: string
            remoteRemappedPodCIDR:
              type: string
            remoteTunnelPrivateIP:
              type: string
            remoteTunnelPublicIP:
              type: string
            tunnelIFaceIndex:
              type: integer
            tunnelIFaceName:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
