# Default values for liqoDash.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: liqo/dashboard
  pullPolicy: Always
agentConfig:
  service: "liqo-dashboard"
  serviceAccount: "liqodash-admin-sa"
  ingress: "liqo-dashboard-ingress"
  appLabel: "liqo-dashboard"
  # Overrides the image tag whose default is the chart appVersion.

suffix: ""
version: "latest"
