---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: resourceslices.authentication.liqo.io
spec:
  group: authentication.liqo.io
  names:
    categories:
    - liqo
    kind: ResourceSlice
    listKind: ResourceSliceList
    plural: resourceslices
    singular: resourceslice
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ResourceSlice represents a slice of resources given by the provider
          cluster to the consumer cluster.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ResourceSliceSpec defines the desired state of ResourceSlice.
            properties:
              class:
                description: Class contains the class of the ResourceSlice.
                type: string
              consumerClusterIdentity:
                description: ConsumerClusterIdentity is the identity of the consumer
                  cluster.
                properties:
                  clusterID:
                    description: Foreign Cluster ID, this is a unique identifier of
                      that cluster.
                    type: string
                  clusterName:
                    description: Foreign Cluster Name to be shown in GUIs.
                    type: string
                required:
                - clusterID
                - clusterName
                type: object
              csr:
                description: CSR is the Certificate Signing Request of the consumer
                  cluster.
                type: string
              providerClusterIdentity:
                description: ProviderClusterIdentity is the identity of the provider
                  cluster.
                properties:
                  clusterID:
                    description: Foreign Cluster ID, this is a unique identifier of
                      that cluster.
                    type: string
                  clusterName:
                    description: Foreign Cluster Name to be shown in GUIs.
                    type: string
                required:
                - clusterID
                - clusterName
                type: object
              resources:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: Resources contains the slice of resources requested.
                type: object
            type: object
          status:
            description: ResourceSliceStatus defines the observed state of ResourceSlice.
            properties:
              authParams:
                description: AuthParams contains the authentication parameters for
                  the resources given by the provider cluster.
                properties:
                  apiServer:
                    type: string
                  awsConfig:
                    description: AwsConfig contains the AWS configuration and access
                      key for the Liqo user and the current EKS cluster.
                    properties:
                      awsAccessKeyID:
                        type: string
                      awsClusterName:
                        type: string
                      awsRegion:
                        type: string
                      awsSecretAccessKey:
                        type: string
                    required:
                    - awsAccessKeyID
                    - awsClusterName
                    - awsRegion
                    - awsSecretAccessKey
                    type: object
                  ca:
                    format: byte
                    type: string
                  signedCRT:
                    format: byte
                    type: string
                type: object
              condition:
                description: Condition contains the condition of the ResourceSlice.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime -> timestamp for when the condition
                      last transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message -> Human-readable message indicating details
                      about the last status transition.
                    type: string
                  reason:
                    description: Reason -> Machine-readable, UpperCamelCase text indicating
                      the reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition.
                    enum:
                    - Accepted
                    - Denied
                    type: string
                required:
                - status
                type: object
              resources:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: Resources contains the slice of resources accepted.
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
