---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: foreignclusters.discovery.liqo.io
spec:
  group: discovery.liqo.io
  names:
    categories:
    - liqo
    kind: ForeignCluster
    listKind: ForeignClusterList
    plural: foreignclusters
    singular: foreigncluster
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.peeringType
      name: Type
      type: string
    - jsonPath: .spec.clusterIdentity.clusterID
      name: ClusterID
      priority: 1
      type: string
    - jsonPath: .spec.clusterIdentity.clusterName
      name: ClusterName
      priority: 1
      type: string
    - jsonPath: .status.peeringConditions[?(@.type == 'OutgoingPeering')].status
      name: Outgoing peering
      type: string
    - jsonPath: .status.peeringConditions[?(@.type == 'IncomingPeering')].status
      name: Incoming peering
      type: string
    - jsonPath: .status.peeringConditions[?(@.type == 'NetworkStatus')].status
      name: Networking
      type: string
    - jsonPath: .status.peeringConditions[?(@.type == 'APIServerStatus')].status
      name: API Server
      priority: 1
      type: string
    - jsonPath: .status.peeringConditions[?(@.type == 'AuthenticationStatus')].status
      name: Authentication
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ForeignCluster is the Schema for the foreignclusters API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ForeignClusterSpec defines the desired state of ForeignCluster.
            properties:
              clusterIdentity:
                description: Foreign Cluster Identity.
                properties:
                  clusterID:
                    description: Foreign Cluster ID, this is a unique identifier of
                      that cluster.
                    type: string
                  clusterName:
                    description: Foreign Cluster Name to be shown in GUIs.
                    type: string
                required:
                - clusterID
                - clusterName
                type: object
              foreignAuthUrl:
                description: URL where to contact foreign Auth service.
                pattern: https:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)
                type: string
              foreignProxyUrl:
                description: URL where to contact foreign proxy for the api server.
                  This URL is used when creating the k8s clients toward the remote
                  cluster.
                type: string
              incomingPeeringEnabled:
                default: Auto
                description: Allow the remote cluster to establish a peering with
                  our cluster.
                enum:
                - Auto
                - "No"
                - "Yes"
                type: string
              insecureSkipTLSVerify:
                default: true
                description: Indicates if the local cluster has to skip the tls verification
                  over the remote Authentication Service or not.
                type: boolean
              outgoingPeeringEnabled:
                default: Auto
                description: Enable the peering process to the remote cluster.
                enum:
                - Auto
                - "No"
                - "Yes"
                type: string
              peeringType:
                default: OutOfBand
                description: The type of peering to be established.
                enum:
                - OutOfBand
                - InBand
                type: string
              ttl:
                description: If discoveryType is LAN, this indicates the number of
                  seconds after that this ForeignCluster will be removed if no updates
                  have been received.
                minimum: 0
                type: integer
            required:
            - foreignAuthUrl
            type: object
          status:
            description: ForeignClusterStatus defines the observed state of ForeignCluster.
            properties:
              apiServerUrl:
                description: URL of the forign cluster's API server.
                type: string
              peeringConditions:
                description: PeeringConditions contains the conditions about the peering
                  related to this ForeignCluster.
                items:
                  description: PeeringCondition contains details about state of the
                    peering.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime -> timestamp for when the condition
                        last transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: Message -> Human-readable message indicating details
                        about the last status transition.
                      type: string
                    reason:
                      description: Reason -> Machine-readable, UpperCamelCase text
                        indicating the reason for the condition's last transition.
                      type: string
                    status:
                      default: None
                      description: Status of the condition.
                      enum:
                      - None
                      - Pending
                      - Established
                      - Disconnecting
                      - Denied
                      - EmptyDenied
                      - Error
                      - Success
                      - External
                      type: string
                    type:
                      description: Type of the peering condition.
                      enum:
                      - OutgoingPeering
                      - IncomingPeering
                      - NetworkStatus
                      - APIServerStatus
                      - AuthenticationStatus
                      - ProcessForeignClusterStatus
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              tenantNamespace:
                description: TenantNamespace names in the peered clusters
                properties:
                  local:
                    description: local TenantNamespace name
                    type: string
                  remote:
                    description: remote TenantNamespace name
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
