---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: tunnelendpoints.net.liqo.io
spec:
  group: net.liqo.io
  names:
    categories:
    - liqo
    kind: TunnelEndpoint
    listKind: TunnelEndpointList
    plural: tunnelendpoints
    singular: tunnelendpoint
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.clusterIdentity.clusterName
      name: Peering Cluster
      type: string
    - jsonPath: .spec.endpointIP
      name: Endpoint IP
      priority: 1
      type: string
    - jsonPath: .spec.backendType
      name: Backend type
      type: string
    - jsonPath: .status.connection.latency.value
      name: Latency
      priority: 1
      type: string
    - jsonPath: .status.connection.status
      name: Connection status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TunnelEndpoint is the Schema for the endpoints API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TunnelEndpointSpec defines the desired state of TunnelEndpoint.
            properties:
              backend_config:
                additionalProperties:
                  type: string
                description: Connection parameters.
                type: object
              backendType:
                description: Vpn technology used to interconnect two clusters.
                type: string
              clusterIdentity:
                description: The identity of the remote cluster.
                properties:
                  clusterID:
                    description: Foreign Cluster ID, this is a unique identifier of
                      that cluster.
                    type: string
                  clusterName:
                    description: Foreign Cluster Name to be shown in GUIs.
                    type: string
                required:
                - clusterID
                - clusterName
                type: object
              endpointIP:
                description: Public IP of the node where the VPN tunnel is created.
                type: string
              localExternalCIDR:
                description: ExternalCIDR of local cluster.
                type: string
              localNATExternalCIDR:
                default: None
                description: Network used in the remote cluster to map the local ExternalCIDR,
                  in case of conflicts (in the remote cluster).
                type: string
              localNATPodCIDR:
                default: None
                description: Network used in the remote cluster to map the local PodCIDR,
                  in case of conflicts (in the remote cluster).
                type: string
              localPodCIDR:
                description: PodCIDR of local cluster.
                type: string
              remoteExternalCIDR:
                description: ExternalCIDR of remote cluster.
                type: string
              remoteNATExternalCIDR:
                default: None
                description: Network used in the local cluster to map the remote cluster
                  ExternalCIDR, in case of conflicts with RemoteExternalCIDR.
                type: string
              remoteNATPodCIDR:
                default: None
                description: Network used in the local cluster to map the remote cluster
                  PodCIDR, in case of conflicts with RemotePodCIDR.
                type: string
              remotePodCIDR:
                description: PodCIDR of remote cluster.
                type: string
            required:
            - backendType
            - backend_config
            - clusterIdentity
            - endpointIP
            - localExternalCIDR
            - localPodCIDR
            - remoteExternalCIDR
            - remotePodCIDR
            type: object
          status:
            description: TunnelEndpointStatus defines the observed state of TunnelEndpoint.
            properties:
              connection:
                description: Connection holds the configuration and status of a vpn
                  tunnel connecting to remote cluster.
                properties:
                  latency:
                    description: ConnectionLatency represents the latency between
                      two clusters.
                    properties:
                      timestamp:
                        format: date-time
                        type: string
                      value:
                        type: string
                    type: object
                  peerConfiguration:
                    additionalProperties:
                      type: string
                    type: object
                  status:
                    description: ConnectionStatus type that describes the status of
                      vpn connection with a remote cluster.
                    type: string
                  statusMessage:
                    type: string
                type: object
              gatewayIP:
                type: string
              tunnelIFaceIndex:
                type: integer
              tunnelIFaceName:
                type: string
              vethIFaceIndex:
                type: integer
              vethIFaceName:
                type: string
              vethIP:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
