---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: natmappings.net.liqo.io
spec:
  group: net.liqo.io
  names:
    categories:
    - liqo
    kind: NatMapping
    listKind: NatMappingList
    plural: natmappings
    singular: natmapping
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NatMapping is the Schema for the natmappings API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NatMappingSpec defines the desired state of NatMapping.
            properties:
              clusterID:
                description: ClusterID is the cluster this resource refers to.
                type: string
              clusterMappings:
                additionalProperties:
                  type: string
                description: ClusterMappings is the set of NAT mappings currently
                  active.
                type: object
              externalCIDR:
                description: ExternalCIDR is the ExternalCIDR used in the remote cluster
                  for local exported resource. It can be either the LocalExternalCIDR
                  or the LocalNATExternalCIDR.
                type: string
              podCIDR:
                description: PodCIDR is the network used for remote pods in the local
                  cluster. It can be either the RemotePodCIDR or the RemoteNATPodCIDR.
                type: string
            required:
            - clusterID
            - clusterMappings
            - externalCIDR
            - podCIDR
            type: object
          status:
            description: NatMappingStatus defines the observed state of NatMapping.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
