---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: firewallconfigurations.networking.liqo.io
spec:
  group: networking.liqo.io
  names:
    categories:
    - liqo
    kind: FirewallConfiguration
    listKind: FirewallConfigurationList
    plural: firewallconfigurations
    singular: firewallconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FirewallConfiguration contains a rule to be applied to the firewall
          in the gateway.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FirewallConfigurationSpec defines the desired state of FirewallConfiguration.
            properties:
              table:
                description: Table contains the rules to be applied to the firewall.
                properties:
                  chains:
                    description: Chains is a list of chains to be applied to the table.
                    items:
                      description: Chain is a chain of rules to be applied to a table.
                      properties:
                        hook:
                          description: Hook specifies at which step in packet processing
                            the Chain should be executed.
                          enum:
                          - prerouting
                          - input
                          - forward
                          - output
                          - postrouting
                          - ingress
                          type: string
                        name:
                          description: Name is the name of the chain.
                          type: string
                        policy:
                          description: Policy defines what this chain default policy
                            will be.
                          enum:
                          - drop
                          - accept
                          type: string
                        priority:
                          default: 0
                          description: Priority orders the chain relative to Netfilter
                            internal operations.
                          format: int32
                          type: integer
                        rules:
                          description: Rules is a list of rules to be applied to the
                            chain.
                          properties:
                            filterRules:
                              description: FilterRules is a list of rules to be applied
                                to the chain.
                              items:
                                description: FilterRule is a rule to be applied to
                                  a filter chain.
                                type: object
                              type: array
                            natRules:
                              description: NatRules is a list of rules to be applied
                                to the chain.
                              items:
                                description: NatRule is a rule to be applied to a
                                  NAT chain.
                                type: object
                              type: array
                            routeRules:
                              description: RouteRules is a list of rules to be applied
                                to the chain.
                              items:
                                description: RouteRule is a rule to be applied to
                                  a route chain.
                                type: object
                              type: array
                          type: object
                        type:
                          description: Type defines what this chain will be used for.
                          enum:
                          - filter
                          - route
                          - nat
                          type: string
                      type: object
                    type: array
                  family:
                    description: Family is the family of the table.
                    enum:
                    - INET
                    - IPV4
                    - IPV6
                    - ARP
                    - NETDEV
                    - BRIDGE
                    type: string
                  name:
                    description: Name is the name of the table.
                    type: string
                type: object
            type: object
          status:
            description: FirewallConfigurationStatus defines the observed state of
              FirewallConfiguration.
            properties:
              condition:
                description: Applied is true if the configuration has been applied
                  to the firewall.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
