---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: configurations.networking.liqo.io
spec:
  group: networking.liqo.io
  names:
    categories:
    - liqo
    kind: Configuration
    listKind: ConfigurationList
    plural: configurations
    shortNames:
    - conf
    singular: configuration
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.remote.cidr.pod
      name: 'Desired Pod CIDR '
      type: string
    - jsonPath: .status.remote.cidr.pod
      name: Remapped Pod CIDR
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.remote.cidr.external
      name: Desired External CIDR
      priority: 1
      type: string
    - jsonPath: .status.remote.cidr.external
      name: Remapped External CIDR
      priority: 1
      type: string
    - jsonPath: .metadata.labels.liqo\.io/remote-cluster-id
      name: ClusterID
      priority: 1
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: |-
          Configuration contains the network configuration of a pair of clusters,
          including the local and the remote pod and external CIDRs and how the where remapped.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ConfigurationSpec defines the desired state of Configuration.
            properties:
              local:
                description: Local network configuration (the cluster where the resource
                  is created).
                properties:
                  cidr:
                    description: CIDR of the cluster.
                    properties:
                      external:
                        description: External CIDR of the cluster.
                        format: cidr
                        type: string
                      pod:
                        description: Pod CIDR of the cluster.
                        format: cidr
                        type: string
                    type: object
                type: object
              remote:
                description: Remote network configuration (the other cluster).
                properties:
                  cidr:
                    description: CIDR of the cluster.
                    properties:
                      external:
                        description: External CIDR of the cluster.
                        format: cidr
                        type: string
                      pod:
                        description: Pod CIDR of the cluster.
                        format: cidr
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: ConfigurationStatus defines the observed state of Configuration.
            properties:
              remote:
                description: Remote remapped configuration, it defines how the local
                  cluster sees the remote cluster.
                properties:
                  cidr:
                    description: CIDR of the cluster.
                    properties:
                      external:
                        description: External CIDR of the cluster.
                        format: cidr
                        type: string
                      pod:
                        description: Pod CIDR of the cluster.
                        format: cidr
                        type: string
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
