name: Integration Pipeline
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
        - virtual-kubelet
        - liqonet
        - advertisement-broadcaster
        - advertisement-operator
        - init-vkubelet
        - scheduling-node-operator
        - discovery
        - peering-request-operator
        - secret-creation
        - init-pod-mutator
        - pod-mutator
        - peering-request-webhook-init
        - crdReplicator
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        if: github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
      - name: Set the commit to build
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "commit_ref=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          elif [ ! -z ${{ steps.get_version.outputs.VERSION }} ]; then
            echo "commit_ref=${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_ENV
          else
            echo "commit_ref=${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: "${{ env.commit_ref }}"

      - name: Push ${{ matrix.component }} image (unversioned)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: liqo/${{ matrix.component }}-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: build/${{ matrix.component }}/Dockerfile
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.commit_ref }}"
        if: github.event.repository.full_name == 'liqotech/liqo' && !startsWith(github.ref, 'refs/tags/v')

      - name: Build and Publish ${{ matrix.component }} image (Versioned)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: liqo/${{ matrix.component }}
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: build/${{ matrix.component }}/Dockerfile
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.get_version.outputs.VERSION }}"
        if: github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')

      - name: Build Only ${{ matrix.component }} image (Forked Repositories)
        uses: docker/build-push-action@v1
        with:
          name: liqo/${{ matrix.component }}-ci
          dockerfile: build/${{ matrix.component }}/Dockerfile
          push: false
        if: github.ref != 'refs/heads/master' && github.event.pull_request.head.repo.full_name != 'liqotech/liqo' &&
            !startsWith(github.ref, 'refs/tags/v')

  e2e-test-trigger:
     runs-on: ubuntu-latest
     needs: [build]
     strategy:
       fail-fast: false
       matrix:
         component:
         - liqops
         - doc-website
     steps:
       - name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
         if: github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
       - name: Set the commit to build
         run: |
           if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
              echo "commit_ref=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
           else
              echo "commit_ref=${{ github.sha }}" >> $GITHUB_ENV
           fi
       - uses: actions/checkout@v2
         with:
           ref: "${{ env.commit_ref }}"
       - name: "Make scripts executable"
         run: chmod +x ./scripts/utils/*
       - name: "Set PR number"
         run: echo "branch_owner=`git log -1 --format='%ae' $commit_ref^!`"
       - name: "Install python dependencies"
         run: pip install requests
       - name: "Set branch name"
         run: echo "branch_name=`echo ${GITHUB_REF#refs/*/}`" >> $GITHUB_ENV
       - name: "Notify PR Event to Liqops"
         run: |
           curl -X POST https://api.github.com/repos/liqotech/${{ matrix.component }}/dispatches \
           -u ${{ secrets.CI_TOKEN }} \
           --data '{"event_type": "dev-event", "client_payload": { "actor": "${{ env.branch_owner }}", "version": "${{ steps.get_version.outputs.VERSION }}", "commit": "${{ env.commit_ref }}" }}'
     if: github.event.pull_request.draft == false

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'push' && github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # The changelog generation requires the entire history
          fetch-depth: 0
          persist-credentials: false

      - name: Get the Liqo version to be released
        id: version
        run: echo "version::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get the latest Liqo release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: last-release
        with:
          repository: ${{ github.repository }}

      - name: Generate the CHANGELOG
        uses: RiskLedger/generate-changelog@v1.2
        id: changelog
        with:
          from: ${{ steps.last-release.outputs.release }}
          to: ${{ steps.version.outputs.version }}
        env:
          GITHUB_AUTH: ${{ secrets.CI_TOKEN }}

      - name: Save the CHANGELOG as a file
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > ./CHANGELOG.md
          sed -i "1s/.*/## Changes since ${{ steps.last-release.outputs.release }}/" ./CHANGELOG.md

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.test.outputs.release_version }}
          release_name: ${{ needs.test.outputs.release_version }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

# Agent Upload Artifact
      - name: Download Agent artifact
        uses: actions/download-artifact@v2
        with:
          name: agent_artifact

      - name: Upload Agent asset to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: liqo-agent.tar.gz
          asset_content_type: application/gzip
          github_token: ${{ secrets.CI_TOKEN }}
          overwrite: true

  test:
    name: Launch Test and Build Liqo Agent
    runs-on: ubuntu-20.04
    outputs:
      release_version: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: Get the version
      id: get_version
      run: echo "::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)"
      if: github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')

    - name: Set the commit to build
      run: |
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
           echo "commit_ref=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        elif [ ! -z ${{ steps.get_version.outputs.VERSION }} ]; then
           echo "commit_ref=${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_ENV
        else
           echo "commit_ref=${{ github.sha }}" >> $GITHUB_ENV
        fi
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: "${{ env.commit_ref }}"
    - name: Install Kubebuilder
      run: |
        version=2.3.1 # latest stable version
        arch=amd64
        curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz"
        tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
        mv kubebuilder_${version}_linux_${arch} kubebuilder && sudo mv kubebuilder /usr/local/
        export PATH=$PATH:/usr/local/kubebuilder/bin
    - name: Get dependencies
      run: |
        go get -u github.com/ory/go-acc
        go get -u github.com/cratonica/2goarray
    - name: install tray-agent dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update && sudo apt -y upgrade
        sudo apt-get -y install gcc libgtk-3-dev libappindicator3-dev libxapp-dev libwebkit2gtk-4.0-dev xclip
    - name: generate tray-agent icons
      run: |
        chmod +x ./scripts/tray-agent/make_icon.sh
        ./scripts/tray-agent/make_icon.sh
    - run: go-acc ./... --ignore liqo/test/e2e
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt
    - name: Build Agent asset
      run: |
        GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build ./cmd/tray-agent/liqo-agent.go
        tar -czf liqo-agent.tar.gz liqo-agent
      if: github.event_name == 'push' && github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
    - name: Upload Agent artifact
      uses: actions/upload-artifact@v2
      with:
        name: agent_artifact
        path: liqo-agent.tar.gz
        retention-days: 1
        if-no-files-found: error
      if: github.event_name == 'push' && github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
    if: github.event.pull_request.draft == false
