name: Add Size Label to PR
on:
  pull_request

jobs:
  build:
    name: Add Size Label to PR
    runs-on: ubuntu-latest
    steps:
      - name: Add Size Label to PR
        uses: WizardOhio24/label-pr-size-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
